import './globals.css';
import Header from '@/components/layout/Header';
import { Manrope } from 'next/font/google'

export const metadata = {
  title: 'Panaverse Dao',
  description: 'Generated by create next app',
}

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
