'use client';
import './globals.css';
import Header from '@/components/layout/Header';
import { Manrope } from 'next/font/google'

export const metadata = {
  title: 'Panaverse Dao',
  description: 'Generated by create next app',
}

const manrope = Manrope({
  weight: ['300', '400', '500', '600', '700', '800'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-manrope',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <style jsx global>{`
        html {
          font-family: ${manrope.style.fontFamily};
        }
      `}</style>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
